apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wroj8vnic-python 
  janus-idp.io/tekton: wroj8vnic-python
  backstage.io/kubernetes-id: wroj8vnic-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wroj8vnic-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  